language: node_js
node_js:
  - "8"

branches:
  only:
    - develop

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - npm install
  - npm run build
  - npm run deploy