language: node_js
node_js:
  - "8"

branches:
  only:
    - develop

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - npm run build
  - npx ngh --repo=https://GH_TOKEN@github.com/Code-Book/Code-Book.github.io.git --branch=master --dir=dist/Code-Book-Landing